//
//  * Created by willian levandoski on 13/09/21.
//

public class AccountTransportadorasResquestTemplate {

public List<Transportadoras> Transportadoras;

	public class Transportadoras {
		public String CodEmp;
		public String CodFil;
		public String TpCadastro;
		public String Codemitente;
		public String nomeemit;
		public String nomeabrev;
		public String endereco;
		public String bairro;
		public String estado;
		public String cidade;
		public String paisbacen;
		public String email;
		public String cep;
		public String ddd;
		public String tel;
		public String cnpj;
		public String ie;
		public String hPage;
		public String ibgecidade;
		public String complemento;
	}
}