public class AccountPreIntegrableRequestTemplate{
	public String A1_PESSOA;	//J
	public String A1_TIPO;	//F
	public String A1_NOME;	//TESTEUF2
	public String A1_NREDUZ;	//TESEUFUF2
	public String A1_CGC;	//
	public String A1_CEP;	//5467000
	public String A1_END;	//R BERLIOZ, 225
	public String A1_BAIRRO;	//ALTO DE PINHEIROS
	public String A1_MUN;	//SAO PAULO
	public String A1_EST;	//SP
    
    /*public IMPOSTOS IMPOSTOS;
    
    public class IMPOSTOS{
        public String A1_NATUREZ; //6101 ,
		public Integer A1_CONTRIB; //1,
		public Double A1_ALIQ; // 2.2
        
    }*/
	
}