/**
 * Created by willian levandoski on 01/09/21.
 */

public with sharing class AccountIntegrableRequestTemplate {
    public List<Clientes> Clientes;

	public class Clientes {
		public String CodEmp;
		public String CodFil;
		public String TpCadastro;
		public String Cod_emitente;
		public String Cod_estabel;
		public String nome_emit;
		public String nome_abrev;
		public String endereco;
		public String bairro;
		public String estado;
		public String cidade;
		public String ibgecidade;
		public String pais;
		public String paisbacen;
		public String email;
		public String tipo;
		public String ccontabil;
		public String pessoa;
		public String cep;
		public String ddd;
		public String telefone;
		public String contato;
		public String cnpj;
		public String ie;
		public String im;
		public String site;
		public String status;
		public String codmunentrega;
		public String endentrega;
		public String bairroentrega;
		public String munentrega;
		public String estentrega;
		public String cepentrega;
		public String simpnacional;
		public String DtAbertura;
		public String Complemento;
		public String CompEntrega;
		public String Natureza;
		public String Suframa;
		public String Vendedor;
		public String FomeZero;
		public String Contribuinte;
		public String TipoPessoa;
		public String RamoAtividade;
	}
}