public class DW_SintegraResponse_RF{
	public String code;	//0
	public String status;	//OK
	public String message;	//Pesquisa realizada com sucesso.
	public String cnpj;	//17.359.233/0001-88
	public String nome;	//TECIDOS E ARMARINHOS MIGUEL BARTOLOMEU S/A
	public String fantasia;	//TAMBASA ATACADISTAS
	public String cep;	//32.060-514
	public String uf;	//MG
	public String municipio;	//Contagem
	public String bairro;	//TAPERA
	public String tipo_logradouro;
	public String logradouro;	//V MUNICIPAL MANOEL JACINTO COELHO JR
	public String numero;	//S/N
	public String complemento;	//********
	public String telefone;	//(31) 3359-0000
	public String email;	//contabilidade@tambasa.com.br
	public String capital_social;	//3830000.00
	public String data_situacao;	//24/09/2005
	public String data_situacao_especial;	//********
	public String abertura;	//11/12/1968
	public String motivo_situacao;	//
	public String sigla_natureza_juridica;	//s/a
	public String natureza_juridica;	//204-6 - Sociedade Anônima Aberta
	public String situacao;	//ATIVA
	public String situacao_especial;	//********
	public String tipo;	//MATRIZ
	public cls_atividade_principal[] atividade_principal;
	public cls_atividades_secundarias[] atividades_secundarias;
	public cls_qsa[] qsa;
	public String ultima_atualizacao;	//25/04/2023 16:28:32
	public String efr;	//*****
	// public cls_extra extra;
	public String porte;	//DEMAIS
	public cls_ibge ibge;
	public cls_cnpjs_do_grupo[] cnpjs_do_grupo;
	public String inscricao_municipal;	//
	public cls_coordinates coordinates;
	public String version;	//5
	public class cls_tipo_logradouro {
	}
	public class cls_atividade_principal {
		public String code;	//4689399
		public String text;	//Comércio atacadista especializado em outros produtos intermediários não especificados anteriormente
	}
	public class cls_atividades_secundarias {
		public String code;	//4530701
		public String text;	//Comércio por atacado de peças e acessórios novos para veículos automotores
	}
	public class cls_qsa {
		public String qual;	//10-Diretor
		// public cls_qual_rep_legal qual_rep_legal;
		// public cls_nome_rep_legal nome_rep_legal;
		// public cls_pais_origem pais_origem;
		public String nome;	//GUSTAVO BITTENCOURT BARTOLOMEU
		// public cls_faixa_etaria faixa_etaria;
	}
	// class cls_qual_rep_legal {
	// }
	// class cls_nome_rep_legal {
	// }
	// class cls_pais_origem {
	// }
	// class cls_faixa_etaria {
	// }
	// class cls_extra {
	// }
	public class cls_ibge {
		public String codigo_municipio;	//3118601
		public String codigo_uf;	//31
	}
	public class cls_cnpjs_do_grupo {
	}
	public class cls_coordinates {
		public String latitude;	//-19.8615131
		public String longitude;	//-44.1309268
	}
}