public class GetSintegraWSIntegrableTempate{
	public String code;	//0
	public String status;	//OK
	public String message;	//Pesquisa realizada com sucesso.
	public String cnpj;	//06990590000123
	public String inscricao_estadual;	//149848403115
	public String nome_empresarial;	//Google brasil internet ltda.
	public String nome_fantasia;	//
	public String situacao_cnpj;	//Ativo
	public String situacao_ie;	//Ativo
	public cls_situacao_ie_desc situacao_ie_desc;
	public cls_cnae_principal cnae_principal;
	public String cep;	//04538133
	public String uf;	//SP
	public String municipio;	//São Paulo
	public String bairro;	//Itaim bibi
	public String logradouro;	//Avenida brig faria lima
	public String numero;	//3477
	public String complemento;	//Andar 17a20 tsul 2 17a20
	public String regime_tributacao;	//Normal - regime periódico de apuração
	public String informacao_ie_como_destinatario;	//Obrigatoriedade total
	public String porte_empresa;	//Não informado
	public String tipo_inscricao;	//
	public String data_inicio_atividade;	//16-10-2007
	public String data_fim_atividade;	//
	public String data_situacao_cadastral;	//16-10-2007
	public boolean contribuinte_icms;
	public cls_ibge ibge;
	public boolean ccc;
	public String version;	//5
	public class cls_situacao_ie_desc {
	}
	public class cls_cnae_principal {
		public String code;	//0
		public String text;	//
	}
	public class cls_ibge {
		public String codigo_municipio;	//3550308
		public String codigo_uf;	//35
	}
	
}