public class Product2MercosIntegrableRequestTemplate{
	public String nome;	//Furadeira de Impacto HGSB13
	public Double preco_tabela;	//254.87
	public cls_preco_minimo preco_minimo;
	public String codigo;	//003
	public cls_comissao comissao;
	public Double ipi;
	public String tipo_ipi;	//P
	public cls_st st;
	public String moeda;	//0
	public String unidade;	//Un
	public cls_saldo_estoque saldo_estoque;
	public String observacoes;	//
	public cls_grade_cores[] grade_cores;
	public cls_grade_tamanhos grade_tamanhos;
	public boolean excluido;
	public boolean ativo;
	public Integer categoria_id;	//1
	public String codigo_ncm;	//2201.10.00
	public cls_multiplo multiplo;
	public Double peso_bruto;	//3.351
	public Double largura;	//10.123
	public Double altura;	//25.12467
	public Double comprimento;	//10.123
	public boolean peso_dimensoes_unitario;
	public boolean exibir_no_b2b;
	public class cls_preco_minimo {
	}
	public class cls_comissao {
	}
	
	public class cls_st {
	}
	public class cls_saldo_estoque {
	}
	public class cls_grade_cores {
    }
	public class cls_grade_tamanhos {
	}
	public class cls_multiplo {
	}
	
}