//
// Created by Willian Levandoski 13/09/2021
//

public class VendedoresIntegrableResquestTemplate {

	public List<Vendedores> Vendedores;

	public class Vendedores {
		public String CodEmp;
		public String CodFil;
		public String TpCadastro;
		public String Codemitente;
		public String nomeemit;
		public String nomeabrev;
		public String endereco;
		public String bairro;
		public String estado;
		public String cidade;
		public String pais;
		public String email;
		public String cep;
		public String ddd;
		public String cel;
		public String cnpj;
		public String ie;
		public String status;
		public Decimal comis;
		public Integer pgbaixa;
		public String tipoven;
		public String bicm;
		public String bicmret;
		public String biss;
		public String bipi;
		public String bfrete;
	}
}